# Generated by Django 4.1.4 on 2023-01-01 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_content_alter_board_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, '최소 10글자 이상은 입력해주셔야 합니다.')], verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, '최소 세 글자 이상은 입력해주셔야 합니다.')], verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=255, verbose_name='댓글'),
        ),
    ]
